# Étape de build
FROM node:18-alpine AS builder
WORKDIR /app
# Déclare l'argument de build
ARG REACT_APP_URL
# Définit la variable d'environnement à partir de l'argument
ENV REACT_APP_URL=$REACT_APP_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape de production
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]