version: '3.8'
services:
  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - URL=${URL}
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:80'
    env_file:
      - .env
    environment:
      - REACT_APP_URL=${URL}
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    stdin_open: true
    tty: true